
Epoch 1/5
Traceback (most recent call last):
  File "C:\Users\Lucas\AppData\Local\Temp\ipykernel_26308\414260523.py", line 97, in sweep_train
    train(model,
  File "C:\Users\Lucas\AppData\Local\Temp\ipykernel_26308\414260523.py", line 48, in train
    model.fit(
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Lucas\AppData\Local\Temp\__autograph_generated_filetsa1_r6c.py", line 18, in tf__train_function
    raise
ValueError: in user code:
    File "C:\Users\Lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\training.py", line 1377, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\Lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\training.py", line 1360, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\training.py", line 1349, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\Lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\training.py", line 1130, in train_step
        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "C:\Users\Lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\optimizers\optimizer.py", line 544, in minimize
        self.apply_gradients(grads_and_vars)
    File "C:\Users\Lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\optimizers\optimizer.py", line 1223, in apply_gradients
        return super().apply_gradients(grads_and_vars, name=name)
    File "C:\Users\Lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\optimizers\optimizer.py", line 652, in apply_gradients
        iteration = self._internal_apply_gradients(grads_and_vars)
    File "C:\Users\Lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\optimizers\optimizer.py", line 1253, in _internal_apply_gradients
        return tf.__internal__.distribute.interim.maybe_merge_call(
    File "C:\Users\Lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\optimizers\optimizer.py", line 1345, in _distributed_apply_gradients_fn
        distribution.extended.update(
    File "C:\Users\Lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\optimizers\optimizer.py", line 1342, in apply_grad_to_update_var  **
        return self._update_step(grad, var)
    File "C:\Users\Lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\optimizers\optimizer.py", line 241, in _update_step
        self.update_step(gradient, variable)
    File "C:\Users\Lucas\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\optimizers\adam.py", line 204, in update_step
        variable.assign_sub((m * alpha) / (tf.sqrt(v) + self.epsilon))
    ValueError: Dimensions must be equal, but are 28 and 3 for '{{node Adam/mul_3}} = Mul[T=DT_FLOAT](Adam/ReadVariableOp_2, Adam/truediv)' with input shapes: [5,5,1,28], [3].